title: "Team Red/Blue"
baseurl: "/"
url: "https://redblue.github.io"

header_pages:
  - index.md
  - about.md
  - writeup.md
  - red.md
  - blue.md
  
style: dark

footer: 'Bize Yazın <a href="mailto://7r157@protonmail.com">Mail</a>'

# Build settings
markdown: kramdown
